<?php
$title = "Books";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<div>
    <a href="<?php echo $this->url('book')?>">
    	&laquo; List all books
    </a>
</div>

<?php
if(isset($messagesFlash[0]))
{
	foreach ($messagesFlash as $key => $message)
	{
		?>
	    <div class="alert alert-<?= $message['class'] ?>">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<?= $message['text'] ?>
	    </div>

		<?php
	}
}
?>

<h2><?php echo ($this->title) ?: 'Enter with file of Books' ?></h2>

<?php
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper
    ->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');
?>
<?php echo $this->form()->openTag($form); ?>
<fieldset>
    <legend><?php echo ($this->legend) ?: 'File Upload' ?></legend>

    <?php
    $elem = $form->get('file');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php echo $errorClass ?>">
        <?php echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php echo $this->formFile($elem); ?>
            <?php echo $errorsHelper($elem); ?>
            <?php if (!empty($this->tempFiles)) { ?>
                <div class="help-block">
                    Uploaded: <ul>
                    <?php foreach ($this->tempFiles as $tempFile) { ?>
                        <li><?php echo $this->escapeHtml($tempFile['name']) ?></li>
                    <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Submit</button>
        </div>
    </div>

</fieldset>
<?php echo $this->form()->closeTag($form); ?>
