<?php
$title = "Authors";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<div>
    <a href="<?php echo $this->url('author', array('action'=> "import"))?>">
    	&raquo; Import authors
    </a>
</div>
<?php 
if($lAuthors)
{
?>

<table class="table">
    <tr>
        <th>Full name</th>
    </tr>
    <?php foreach ($lAuthors as $author) :?>
        <tr>
            <td><?= $this->escapeHtml($author->firstName . ' ' . $author->lastName) ?></td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
}
?>
