<?php
$title = 'Library App';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1>Library App <span class="zf-green">herokuapp</span></h1>
    <p>
        Test 
        <a href="http://www.indt.org.br/" target="_blank">
        INDT
        </a>.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Authors
                </h3>
            </div>
            <div class="panel-body">
                <p>
                    Guide for Authors
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo($this-> basePath("author")); ?>">
                    Authors &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
